AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'Rakefile'
    - 'Guardfile'
    - 'config/application.rb'
    - 'config/environments/*'
    - 'config/initializers/**/*'
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'
    # most of the specs file have long line length but readability is still good

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'
    - 'lib/tasks/**/*'
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/AsciiComments:
  Enabled: false
