redis:
  image: redis:3.2-alpine
  container_name: redis_local
  ports:
    - "6379:6379"
  command: redis-server

dedenne:
  build: .
  container_name: dedenne_local
  ports:
    - "4567:4567"
  environment:
    AWS_S3_ACCESS_KEY_ID: ${AWS_S3_ACCESS_KEY_ID}
    AWS_S3_SECRET_ACCESS_KEY: ${AWS_S3_SECRET_ACCESS_KEY}
  links:
    - redis
  command: foreman start
