require_relative 'dedenne/amazon_service'
require_relative 'dedenne/request_handler'
require_relative 'dedenne/transcoder_queue'
require_relative 'dedenne/video_processor'
require_relative 'dedenne/version'
